site_name: Milan Docs
site_url: https://mhrons.github.io/
nav:
    - About Me: index.md
    - Renewable Energy Sources:
        - RES Impact on Grid: pv_intermit.md
        - RES Power Smoothing: pv_smooth.md
        - Real vs Ideal Smoothing: sim_smooth.md
        - PV Smoothing Diagrams: pv_graph.md
        - SPLPF Smoothing: splpf.md
        - Glossary: v_glossary.md
    - PV Logger: pv_log.md
    - EE pre SŠ:
        - Úvod a elektrické veličiny: EE_veliciny.md
        - Základné zákony: Elektrostatika.md
        - Matematika elektrodynamiky: Matematika.md
        - Indučnosť a kapacita : Reaktancia.md
        - Rezonančný obovd: LC_obvod.md
        - Filtre I. rádu: Filtre_I.md
        - Výkon AC: AC_vykon.md
        - Trojfázová sieť: Trojfaz.md
        - Meniče napätia a prúdu: Transformatory.md
        - Operačné siete: OZ_siete.md
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
  custom_dir: custom_theme/
  include_homepage_in_sidebar: true
  prev_next_buttons_location: bottom
  navigation_depth: 3
  collapse_navigation: false
  titles_only: false

extra_javascript: 
#    - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'    
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
#    - mathjax_config.js

markdown_extensions:
#    - mdx_math
    - attr_list
    - md_in_html
    - meta
    - pymdownx.betterem
#    - pymdownx.arithmatex
    - pymdownx.caret
    - pymdownx.mark
    - pymdownx.tilde
    
watch: 
    - custom_theme/

plugins:
    - search:
    - encryptcontent:
        title_prefix: ' '
        summary: 'SPLPF in theory'
        encryption_info_message: "This content is password-protected"
        arithmatex: True
