site_name: Milan Docs
site_url: https://mhrons.github.io/
nav:
    - About me: index.md
    - Photovoltaic intermitency: pv_log.md
    - Smoothing of PV intermitency: pv_smooth.md
    - Glossary: v_glossary.md
theme:
  name: readthedocs
  custom_dir: custom_theme/
  include_homepage_in_sidebar: true
  prev_next_buttons_location: bottom
  navigation_depth: 4
  collapse_navigation: false
  titles_only: false

extra_javascript: 
#    - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'    
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
#    - mathjax_config.js

markdown_extensions:
#    - mdx_math
    - attr_list
    - md_in_html
    - meta
    - pymdownx.betterem
#    - pymdownx.arithmatex
    - pymdownx.caret
    - pymdownx.mark
    - pymdownx.tilde
    
watch: 
    - custom_theme/

plugins:
    - search:
    - encryptcontent:
        title_prefix: '[LOCK] '
        summary: 'This content is not public'
        encryption_info_message: "Please contact the author for access to this page."
        arithmatex: True
